theme: jekyll-theme-cayman
title: Polish for Tourists
description: Polish language learning lessons aimed at tourists
github:
  keyphrases: keyphrases.html
  aboutPoland: aboutPoland.html
  index: index.html
  advancedPolish: advancedpolish.html
  furtherlinks: furtherlinks.html
