theme: jekyll-theme-cayman
title: Aleks' page
description: This is my page for SML5202
github:
  keyphrases: keyphrases.html
  aboutPoland: aboutPoland.html
  index: index.html
  exercises: exercises.html
